name: address_selector_for_chinese
description: 中国的省市区选择器
version: 0.0.1
author: linty
homepage:
# 以 https://github.com/shenhuaxiyuan/flutter_jd_address_selector 为基础进行修改

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  azlistview: ^2.0.0-nullsafety.0
  lpinyin: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/chinese_cities.json